project_id = "atffouxdlvfmzcjqvvmy"

[functions.get-shared-quiz]
verify_jwt = false

[functions.extract-image-text]
verify_jwt = false

[functions.submit-shared-quiz]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false
